import type { Metadata } from "next";

import "./../globals.css";
import { ThemeProvider } from "next-themes";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ThemeProvider attribute="class" enableSystem={true} defaultTheme="system">
          {children}
      </ThemeProvider>
  );
}
