import type { Metadata } from "next"; 
import { Toaster } from "sonner";


 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        {children}
        <Toaster position="top-right" theme="dark" />
      </body>
    </html>
  );
}
